version: '3.1'

services:

  db:
    image: postgres:11-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dream
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password