# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ apply_nest ]
  pull_request:
    branches: [ apply_nest ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@master
    - name: Launch MongoDB
      uses: wbari/start-mongoDB@master
      with:
        mongoDBVersion: 4.2
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install
        
    - name: Build
      run: |
        npm run heroku-postbuild --if-present
        
    - name: Test
      run: |
        npm run test
